export enum UserRole {
  MAHASISWA = "MAHASISWA",
  MITRA = "MITRA",
  SUPERUSER = "SUPERUSER",
}

export enum VerificationStatus {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
}

export enum MitraVerificationLevel {
  BASIC = "BASIC",
  BUSINESS = "BUSINESS",
  TRUSTED = "TRUSTED",
}

export enum ProjectStatus {
  DRAFT = "DRAFT",
  OPEN_FOR_BID = "OPEN_FOR_BID",
  BID_SELECTED = "BID_SELECTED",
  WAITING_PAYMENT = "WAITING_PAYMENT",
  PAYMENT_SECURED = "PAYMENT_SECURED",
  IN_PROGRESS = "IN_PROGRESS",
  SUBMITTED = "SUBMITTED",
  REVISION_REQUESTED = "REVISION_REQUESTED",
  WAITING_APPROVAL = "WAITING_APPROVAL",
  APPROVED = "APPROVED",
  DISBURSEMENT_PROCESSING = "DISBURSEMENT_PROCESSING",
  COMPLETED = "COMPLETED",
  DISPUTED = "DISPUTED",
  CANCELLED = "CANCELLED",
}

export enum BidStatus {
  SUBMITTED = "SUBMITTED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
}

export enum PaymentStatus {
  UNPAID = "UNPAID",
  PENDING = "PENDING",
  SECURED = "SECURED",
  FAILED = "FAILED",
  EXPIRED = "EXPIRED",
  REFUNDED = "REFUNDED",
}

export enum PayoutStatus {
  NOT_REQUESTED = "NOT_REQUESTED",
  PROCESSING = "PROCESSING",
  PAID_SUCCESSFULLY = "PAID_SUCCESSFULLY",
  FAILED = "FAILED",
  DISPUTED = "DISPUTED",
}

export enum StudentPlan {
  BASIC = "BASIC",
  PRO = "PRO",
}
